stages:
  - test
  - build
  - deploy

variables:
  NODE_ENV: "production"

cache:
  paths:
    - node_modules/

before_script:
  - npm install

lint:
  stage: test
  script:
    - npm run lint

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

docker-build:
  stage: deploy
  script:
    - docker build -t riggerconnect-web .
  only:
    - main
